// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_game
global.__objectDepths[1] = -100; // obj_screen_flash
global.__objectDepths[2] = 0; // obj_view_controller
global.__objectDepths[3] = 0; // obj_particle_creater
global.__objectDepths[4] = 0; // obj_level
global.__objectDepths[5] = 0; // obj_backgrounds_planets
global.__objectDepths[6] = -5; // obj_danger
global.__objectDepths[7] = 0; // obj_ads_video
global.__objectDepths[8] = 0; // obj_ads
global.__objectDepths[9] = 0; // obj_creador_basura
global.__objectDepths[10] = -100; // obj_highscore
global.__objectDepths[11] = 0; // obj_pages
global.__objectDepths[12] = -100; // obj_button_parent
global.__objectDepths[13] = -100; // obj_logo
global.__objectDepths[14] = -100; // obj_quit_button
global.__objectDepths[15] = -102; // obj_menu_button
global.__objectDepths[16] = -100; // obj_music_on_off
global.__objectDepths[17] = -100; // obj_fx_on_off
global.__objectDepths[18] = -102; // obj_start_button
global.__objectDepths[19] = -102; // obj_start_button2
global.__objectDepths[20] = -102; // obj_start_button3
global.__objectDepths[21] = -100; // obj_hp
global.__objectDepths[22] = -100; // obj_score
global.__objectDepths[23] = -102; // vidas
global.__objectDepths[24] = -100; // obj_tabla
global.__objectDepths[25] = -100; // obj_tabla_credits
global.__objectDepths[26] = -103; // obj_tabla_mm
global.__objectDepths[27] = -102; // obj_stars
global.__objectDepths[28] = 0; // obj_mano_page
global.__objectDepths[29] = 0; // obj_mano_page_back
global.__objectDepths[30] = -103; // obj_candado
global.__objectDepths[31] = 0; // obj_basura
global.__objectDepths[32] = 3; // obj_laser_powerup
global.__objectDepths[33] = 3; // obj_powerup_parent
global.__objectDepths[34] = 3; // obj_powerup_hp
global.__objectDepths[35] = 3; // obj_powerup_shield
global.__objectDepths[36] = -1; // obj_MainCharacter
global.__objectDepths[37] = -1; // obj_Laser
global.__objectDepths[38] = -1; // obj_flare
global.__objectDepths[39] = 0; // obj_explotion_mc
global.__objectDepths[40] = -4; // obj_shield
global.__objectDepths[41] = 0; // obj_mc_menu
global.__objectDepths[42] = -2; // obj_torreta_der
global.__objectDepths[43] = -2; // obj_torreta_izq
global.__objectDepths[44] = -2; // obj_torreta_mid
global.__objectDepths[45] = -1; // obj_enemy_one
global.__objectDepths[46] = -1; // obj_enemy_two
global.__objectDepths[47] = -1; // obj_enemy_four
global.__objectDepths[48] = 0; // o_enemy_parent
global.__objectDepths[49] = 0; // o_enemy_spawner
global.__objectDepths[50] = 0; // obj_enemy_laser
global.__objectDepths[51] = -10; // obj_explotion_center
global.__objectDepths[52] = -1; // obj_black_fade
global.__objectDepths[53] = 0; // obj_enemy_three
global.__objectDepths[54] = 0; // obj_enemy_nitro
global.__objectDepths[55] = -10; // obj_damage
global.__objectDepths[56] = 0; // obj_torre_parent
global.__objectDepths[57] = -2; // obj_boss_torre3
global.__objectDepths[58] = -2; // obj_boss_torre2
global.__objectDepths[59] = 2; // obj_boss1
global.__objectDepths[60] = -2; // obj_boss_torre1
global.__objectDepths[61] = -3; // obj_boss_laser
global.__objectDepths[62] = 0; // obj_boss_disparo
global.__objectDepths[63] = 0; // obj_boss2_1
global.__objectDepths[64] = 0; // obj_boss2_2
global.__objectDepths[65] = 0; // obj_boss2_2_1
global.__objectDepths[66] = 0; // obj_boss2_2_2
global.__objectDepths[67] = 1; // obj_boss3_torre1
global.__objectDepths[68] = 1; // obj_boss3_torre2
global.__objectDepths[69] = 2; // obj_boss3
global.__objectDepths[70] = 0; // obj_torre_parent_boss3
global.__objectDepths[71] = -3; // obj_boss3_laser
global.__objectDepths[72] = 2; // obj_boss_4
global.__objectDepths[73] = 3; // obj_boss_4_body
global.__objectDepths[74] = -3; // obj_boss4_laser
global.__objectDepths[75] = -5; // obj_boss_5
global.__objectDepths[76] = -4; // obj_boss_5_2
global.__objectDepths[77] = -3; // obj_boss5_laser
global.__objectDepths[78] = 0; // obj_boss5_laser_2
global.__objectDepths[79] = 0; // obj_teleport
global.__objectDepths[80] = 0; // obj_boss_6
global.__objectDepths[81] = -3; // obj_boss_6_laser_2
global.__objectDepths[82] = 0; // obj_boss6_laser
global.__objectDepths[83] = 0; // obj_explosion_boss_6
global.__objectDepths[84] = 0; // obj_boss_7
global.__objectDepths[85] = 3; // obj_boss7_laser
global.__objectDepths[86] = 1; // obj_boss7_2
global.__objectDepths[87] = 0; // obj_teleport_boss7
global.__objectDepths[88] = -3; // obj_boss7_fase2_2
global.__objectDepths[89] = 0; // obj_boss7_fase2_laser
global.__objectDepths[90] = 2; // obj_boss_8
global.__objectDepths[91] = 0; // obj_boss_8_2
global.__objectDepths[92] = 0; // obj_boss_8_tp
global.__objectDepths[93] = 1; // obj_boss_8_laser
global.__objectDepths[94] = 2; // obj_boss_9
global.__objectDepths[95] = 0; // obj_boss_9_2_laser
global.__objectDepths[96] = 1; // obj_torre_boss_9
global.__objectDepths[97] = 0; // obj_boss_9_2
global.__objectDepths[98] = 0; // obj_boss_9_laser
global.__objectDepths[99] = -1; // obj_boss_10_laser_beam
global.__objectDepths[100] = 0; // obj_boss_10
global.__objectDepths[101] = -100; // obj_scren_flash_laser
global.__objectDepths[102] = -2; // obj_boss_10_torre
global.__objectDepths[103] = -3; // obj_boss_10_laser


global.__objectNames[0] = "obj_game";
global.__objectNames[1] = "obj_screen_flash";
global.__objectNames[2] = "obj_view_controller";
global.__objectNames[3] = "obj_particle_creater";
global.__objectNames[4] = "obj_level";
global.__objectNames[5] = "obj_backgrounds_planets";
global.__objectNames[6] = "obj_danger";
global.__objectNames[7] = "obj_ads_video";
global.__objectNames[8] = "obj_ads";
global.__objectNames[9] = "obj_creador_basura";
global.__objectNames[10] = "obj_highscore";
global.__objectNames[11] = "obj_pages";
global.__objectNames[12] = "obj_button_parent";
global.__objectNames[13] = "obj_logo";
global.__objectNames[14] = "obj_quit_button";
global.__objectNames[15] = "obj_menu_button";
global.__objectNames[16] = "obj_music_on_off";
global.__objectNames[17] = "obj_fx_on_off";
global.__objectNames[18] = "obj_start_button";
global.__objectNames[19] = "obj_start_button2";
global.__objectNames[20] = "obj_start_button3";
global.__objectNames[21] = "obj_hp";
global.__objectNames[22] = "obj_score";
global.__objectNames[23] = "vidas";
global.__objectNames[24] = "obj_tabla";
global.__objectNames[25] = "obj_tabla_credits";
global.__objectNames[26] = "obj_tabla_mm";
global.__objectNames[27] = "obj_stars";
global.__objectNames[28] = "obj_mano_page";
global.__objectNames[29] = "obj_mano_page_back";
global.__objectNames[30] = "obj_candado";
global.__objectNames[31] = "obj_basura";
global.__objectNames[32] = "obj_laser_powerup";
global.__objectNames[33] = "obj_powerup_parent";
global.__objectNames[34] = "obj_powerup_hp";
global.__objectNames[35] = "obj_powerup_shield";
global.__objectNames[36] = "obj_MainCharacter";
global.__objectNames[37] = "obj_Laser";
global.__objectNames[38] = "obj_flare";
global.__objectNames[39] = "obj_explotion_mc";
global.__objectNames[40] = "obj_shield";
global.__objectNames[41] = "obj_mc_menu";
global.__objectNames[42] = "obj_torreta_der";
global.__objectNames[43] = "obj_torreta_izq";
global.__objectNames[44] = "obj_torreta_mid";
global.__objectNames[45] = "obj_enemy_one";
global.__objectNames[46] = "obj_enemy_two";
global.__objectNames[47] = "obj_enemy_four";
global.__objectNames[48] = "o_enemy_parent";
global.__objectNames[49] = "o_enemy_spawner";
global.__objectNames[50] = "obj_enemy_laser";
global.__objectNames[51] = "obj_explotion_center";
global.__objectNames[52] = "obj_black_fade";
global.__objectNames[53] = "obj_enemy_three";
global.__objectNames[54] = "obj_enemy_nitro";
global.__objectNames[55] = "obj_damage";
global.__objectNames[56] = "obj_torre_parent";
global.__objectNames[57] = "obj_boss_torre3";
global.__objectNames[58] = "obj_boss_torre2";
global.__objectNames[59] = "obj_boss1";
global.__objectNames[60] = "obj_boss_torre1";
global.__objectNames[61] = "obj_boss_laser";
global.__objectNames[62] = "obj_boss_disparo";
global.__objectNames[63] = "obj_boss2_1";
global.__objectNames[64] = "obj_boss2_2";
global.__objectNames[65] = "obj_boss2_2_1";
global.__objectNames[66] = "obj_boss2_2_2";
global.__objectNames[67] = "obj_boss3_torre1";
global.__objectNames[68] = "obj_boss3_torre2";
global.__objectNames[69] = "obj_boss3";
global.__objectNames[70] = "obj_torre_parent_boss3";
global.__objectNames[71] = "obj_boss3_laser";
global.__objectNames[72] = "obj_boss_4";
global.__objectNames[73] = "obj_boss_4_body";
global.__objectNames[74] = "obj_boss4_laser";
global.__objectNames[75] = "obj_boss_5";
global.__objectNames[76] = "obj_boss_5_2";
global.__objectNames[77] = "obj_boss5_laser";
global.__objectNames[78] = "obj_boss5_laser_2";
global.__objectNames[79] = "obj_teleport";
global.__objectNames[80] = "obj_boss_6";
global.__objectNames[81] = "obj_boss_6_laser_2";
global.__objectNames[82] = "obj_boss6_laser";
global.__objectNames[83] = "obj_explosion_boss_6";
global.__objectNames[84] = "obj_boss_7";
global.__objectNames[85] = "obj_boss7_laser";
global.__objectNames[86] = "obj_boss7_2";
global.__objectNames[87] = "obj_teleport_boss7";
global.__objectNames[88] = "obj_boss7_fase2_2";
global.__objectNames[89] = "obj_boss7_fase2_laser";
global.__objectNames[90] = "obj_boss_8";
global.__objectNames[91] = "obj_boss_8_2";
global.__objectNames[92] = "obj_boss_8_tp";
global.__objectNames[93] = "obj_boss_8_laser";
global.__objectNames[94] = "obj_boss_9";
global.__objectNames[95] = "obj_boss_9_2_laser";
global.__objectNames[96] = "obj_torre_boss_9";
global.__objectNames[97] = "obj_boss_9_2";
global.__objectNames[98] = "obj_boss_9_laser";
global.__objectNames[99] = "obj_boss_10_laser_beam";
global.__objectNames[100] = "obj_boss_10";
global.__objectNames[101] = "obj_scren_flash_laser";
global.__objectNames[102] = "obj_boss_10_torre";
global.__objectNames[103] = "obj_boss_10_laser";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for